/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard.dashboard'
import { Route as DashboardWhatsappIndexRouteImport } from './routes/_dashboard.whatsapp.index'
import { Route as DashboardWhatsappTagsRouteImport } from './routes/_dashboard.whatsapp.tags'
import { Route as DashboardWhatsappSetupRouteImport } from './routes/_dashboard.whatsapp.setup'
import { Route as DashboardWhatsappReportsRouteImport } from './routes/_dashboard.whatsapp.reports'
import { Route as DashboardWhatsappLiveAgentRouteImport } from './routes/_dashboard.whatsapp.live-agent'
import { Route as DashboardWhatsappInboxRouteImport } from './routes/_dashboard.whatsapp.inbox'
import { Route as DashboardWhatsappContactsRouteImport } from './routes/_dashboard.whatsapp.contacts'
import { Route as DashboardWhatsappChatbotRouteImport } from './routes/_dashboard.whatsapp.chatbot'
import { Route as DashboardIntelligenceRevenueRouteImport } from './routes/_dashboard.intelligence.revenue'
import { Route as DashboardIntelligenceInsightsRouteImport } from './routes/_dashboard.intelligence.insights'
import { Route as DashboardIntelligenceDealCloserRouteImport } from './routes/_dashboard.intelligence.deal-closer'
import { Route as DashboardIntelligenceConversationRouteImport } from './routes/_dashboard.intelligence.conversation'
import { Route as DashboardIntelligenceBrainRouteImport } from './routes/_dashboard.intelligence.brain'
import { Route as DashboardIntelligenceAutopilotRouteImport } from './routes/_dashboard.intelligence.autopilot'
import { Route as DashboardAgentsWorkflowsRouteImport } from './routes/_dashboard.agents.workflows'
import { Route as DashboardAgentsVoiceLabRouteImport } from './routes/_dashboard.agents.voice-lab'
import { Route as DashboardAgentsVoiceHealthRouteImport } from './routes/_dashboard.agents.voice-health'
import { Route as DashboardAgentsStudioRouteImport } from './routes/_dashboard.agents.studio'
import { Route as DashboardAgentsPostCallRouteImport } from './routes/_dashboard.agents.post-call'
import { Route as DashboardAgentsMessagingLabRouteImport } from './routes/_dashboard.agents.messaging-lab'
import { Route as DashboardAgentsKnowledgeRouteImport } from './routes/_dashboard.agents.knowledge'
import { Route as DashboardAgentsHubRouteImport } from './routes/_dashboard.agents.hub'
import { Route as DashboardAgentsDocumentsRouteImport } from './routes/_dashboard.agents.documents'
import { Route as DashboardAgentsAvatarSyncRouteImport } from './routes/_dashboard.agents.avatar-sync'
import { Route as DashboardAgentsAvatarStudioRouteImport } from './routes/_dashboard.agents.avatar-studio'
import { Route as DashboardAgentsAvatarManageRouteImport } from './routes/_dashboard.agents.avatar-manage'
import { Route as DashboardWhatsappTemplatesIndexRouteImport } from './routes/_dashboard.whatsapp.templates.index'
import { Route as DashboardWhatsappCampaignsIndexRouteImport } from './routes/_dashboard.whatsapp.campaigns.index'
import { Route as DashboardWhatsappTemplatesNewRouteImport } from './routes/_dashboard.whatsapp.templates.new'
import { Route as DashboardWhatsappCampaignsNewRouteImport } from './routes/_dashboard.whatsapp.campaigns.new'
import { Route as DashboardAgentsStudioIdRouteImport } from './routes/_dashboard.agents.studio.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWhatsappIndexRoute = DashboardWhatsappIndexRouteImport.update({
  id: '/whatsapp/',
  path: '/whatsapp/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWhatsappTagsRoute = DashboardWhatsappTagsRouteImport.update({
  id: '/whatsapp/tags',
  path: '/whatsapp/tags',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWhatsappSetupRoute = DashboardWhatsappSetupRouteImport.update({
  id: '/whatsapp/setup',
  path: '/whatsapp/setup',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWhatsappReportsRoute =
  DashboardWhatsappReportsRouteImport.update({
    id: '/whatsapp/reports',
    path: '/whatsapp/reports',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardWhatsappLiveAgentRoute =
  DashboardWhatsappLiveAgentRouteImport.update({
    id: '/whatsapp/live-agent',
    path: '/whatsapp/live-agent',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardWhatsappInboxRoute = DashboardWhatsappInboxRouteImport.update({
  id: '/whatsapp/inbox',
  path: '/whatsapp/inbox',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWhatsappContactsRoute =
  DashboardWhatsappContactsRouteImport.update({
    id: '/whatsapp/contacts',
    path: '/whatsapp/contacts',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardWhatsappChatbotRoute =
  DashboardWhatsappChatbotRouteImport.update({
    id: '/whatsapp/chatbot',
    path: '/whatsapp/chatbot',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardIntelligenceRevenueRoute =
  DashboardIntelligenceRevenueRouteImport.update({
    id: '/intelligence/revenue',
    path: '/intelligence/revenue',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardIntelligenceInsightsRoute =
  DashboardIntelligenceInsightsRouteImport.update({
    id: '/intelligence/insights',
    path: '/intelligence/insights',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardIntelligenceDealCloserRoute =
  DashboardIntelligenceDealCloserRouteImport.update({
    id: '/intelligence/deal-closer',
    path: '/intelligence/deal-closer',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardIntelligenceConversationRoute =
  DashboardIntelligenceConversationRouteImport.update({
    id: '/intelligence/conversation',
    path: '/intelligence/conversation',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardIntelligenceBrainRoute =
  DashboardIntelligenceBrainRouteImport.update({
    id: '/intelligence/brain',
    path: '/intelligence/brain',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardIntelligenceAutopilotRoute =
  DashboardIntelligenceAutopilotRouteImport.update({
    id: '/intelligence/autopilot',
    path: '/intelligence/autopilot',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAgentsWorkflowsRoute =
  DashboardAgentsWorkflowsRouteImport.update({
    id: '/agents/workflows',
    path: '/agents/workflows',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAgentsVoiceLabRoute = DashboardAgentsVoiceLabRouteImport.update({
  id: '/agents/voice-lab',
  path: '/agents/voice-lab',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgentsVoiceHealthRoute =
  DashboardAgentsVoiceHealthRouteImport.update({
    id: '/agents/voice-health',
    path: '/agents/voice-health',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAgentsStudioRoute = DashboardAgentsStudioRouteImport.update({
  id: '/agents/studio',
  path: '/agents/studio',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgentsPostCallRoute = DashboardAgentsPostCallRouteImport.update({
  id: '/agents/post-call',
  path: '/agents/post-call',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgentsMessagingLabRoute =
  DashboardAgentsMessagingLabRouteImport.update({
    id: '/agents/messaging-lab',
    path: '/agents/messaging-lab',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAgentsKnowledgeRoute =
  DashboardAgentsKnowledgeRouteImport.update({
    id: '/agents/knowledge',
    path: '/agents/knowledge',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAgentsHubRoute = DashboardAgentsHubRouteImport.update({
  id: '/agents/hub',
  path: '/agents/hub',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgentsDocumentsRoute =
  DashboardAgentsDocumentsRouteImport.update({
    id: '/agents/documents',
    path: '/agents/documents',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAgentsAvatarSyncRoute =
  DashboardAgentsAvatarSyncRouteImport.update({
    id: '/agents/avatar-sync',
    path: '/agents/avatar-sync',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAgentsAvatarStudioRoute =
  DashboardAgentsAvatarStudioRouteImport.update({
    id: '/agents/avatar-studio',
    path: '/agents/avatar-studio',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAgentsAvatarManageRoute =
  DashboardAgentsAvatarManageRouteImport.update({
    id: '/agents/avatar-manage',
    path: '/agents/avatar-manage',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardWhatsappTemplatesIndexRoute =
  DashboardWhatsappTemplatesIndexRouteImport.update({
    id: '/whatsapp/templates/',
    path: '/whatsapp/templates/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardWhatsappCampaignsIndexRoute =
  DashboardWhatsappCampaignsIndexRouteImport.update({
    id: '/whatsapp/campaigns/',
    path: '/whatsapp/campaigns/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardWhatsappTemplatesNewRoute =
  DashboardWhatsappTemplatesNewRouteImport.update({
    id: '/whatsapp/templates/new',
    path: '/whatsapp/templates/new',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardWhatsappCampaignsNewRoute =
  DashboardWhatsappCampaignsNewRouteImport.update({
    id: '/whatsapp/campaigns/new',
    path: '/whatsapp/campaigns/new',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAgentsStudioIdRoute = DashboardAgentsStudioIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardAgentsStudioRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/agents/avatar-manage': typeof DashboardAgentsAvatarManageRoute
  '/agents/avatar-studio': typeof DashboardAgentsAvatarStudioRoute
  '/agents/avatar-sync': typeof DashboardAgentsAvatarSyncRoute
  '/agents/documents': typeof DashboardAgentsDocumentsRoute
  '/agents/hub': typeof DashboardAgentsHubRoute
  '/agents/knowledge': typeof DashboardAgentsKnowledgeRoute
  '/agents/messaging-lab': typeof DashboardAgentsMessagingLabRoute
  '/agents/post-call': typeof DashboardAgentsPostCallRoute
  '/agents/studio': typeof DashboardAgentsStudioRouteWithChildren
  '/agents/voice-health': typeof DashboardAgentsVoiceHealthRoute
  '/agents/voice-lab': typeof DashboardAgentsVoiceLabRoute
  '/agents/workflows': typeof DashboardAgentsWorkflowsRoute
  '/intelligence/autopilot': typeof DashboardIntelligenceAutopilotRoute
  '/intelligence/brain': typeof DashboardIntelligenceBrainRoute
  '/intelligence/conversation': typeof DashboardIntelligenceConversationRoute
  '/intelligence/deal-closer': typeof DashboardIntelligenceDealCloserRoute
  '/intelligence/insights': typeof DashboardIntelligenceInsightsRoute
  '/intelligence/revenue': typeof DashboardIntelligenceRevenueRoute
  '/whatsapp/chatbot': typeof DashboardWhatsappChatbotRoute
  '/whatsapp/contacts': typeof DashboardWhatsappContactsRoute
  '/whatsapp/inbox': typeof DashboardWhatsappInboxRoute
  '/whatsapp/live-agent': typeof DashboardWhatsappLiveAgentRoute
  '/whatsapp/reports': typeof DashboardWhatsappReportsRoute
  '/whatsapp/setup': typeof DashboardWhatsappSetupRoute
  '/whatsapp/tags': typeof DashboardWhatsappTagsRoute
  '/whatsapp/': typeof DashboardWhatsappIndexRoute
  '/agents/studio/$id': typeof DashboardAgentsStudioIdRoute
  '/whatsapp/campaigns/new': typeof DashboardWhatsappCampaignsNewRoute
  '/whatsapp/templates/new': typeof DashboardWhatsappTemplatesNewRoute
  '/whatsapp/campaigns/': typeof DashboardWhatsappCampaignsIndexRoute
  '/whatsapp/templates/': typeof DashboardWhatsappTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/agents/avatar-manage': typeof DashboardAgentsAvatarManageRoute
  '/agents/avatar-studio': typeof DashboardAgentsAvatarStudioRoute
  '/agents/avatar-sync': typeof DashboardAgentsAvatarSyncRoute
  '/agents/documents': typeof DashboardAgentsDocumentsRoute
  '/agents/hub': typeof DashboardAgentsHubRoute
  '/agents/knowledge': typeof DashboardAgentsKnowledgeRoute
  '/agents/messaging-lab': typeof DashboardAgentsMessagingLabRoute
  '/agents/post-call': typeof DashboardAgentsPostCallRoute
  '/agents/studio': typeof DashboardAgentsStudioRouteWithChildren
  '/agents/voice-health': typeof DashboardAgentsVoiceHealthRoute
  '/agents/voice-lab': typeof DashboardAgentsVoiceLabRoute
  '/agents/workflows': typeof DashboardAgentsWorkflowsRoute
  '/intelligence/autopilot': typeof DashboardIntelligenceAutopilotRoute
  '/intelligence/brain': typeof DashboardIntelligenceBrainRoute
  '/intelligence/conversation': typeof DashboardIntelligenceConversationRoute
  '/intelligence/deal-closer': typeof DashboardIntelligenceDealCloserRoute
  '/intelligence/insights': typeof DashboardIntelligenceInsightsRoute
  '/intelligence/revenue': typeof DashboardIntelligenceRevenueRoute
  '/whatsapp/chatbot': typeof DashboardWhatsappChatbotRoute
  '/whatsapp/contacts': typeof DashboardWhatsappContactsRoute
  '/whatsapp/inbox': typeof DashboardWhatsappInboxRoute
  '/whatsapp/live-agent': typeof DashboardWhatsappLiveAgentRoute
  '/whatsapp/reports': typeof DashboardWhatsappReportsRoute
  '/whatsapp/setup': typeof DashboardWhatsappSetupRoute
  '/whatsapp/tags': typeof DashboardWhatsappTagsRoute
  '/whatsapp': typeof DashboardWhatsappIndexRoute
  '/agents/studio/$id': typeof DashboardAgentsStudioIdRoute
  '/whatsapp/campaigns/new': typeof DashboardWhatsappCampaignsNewRoute
  '/whatsapp/templates/new': typeof DashboardWhatsappTemplatesNewRoute
  '/whatsapp/campaigns': typeof DashboardWhatsappCampaignsIndexRoute
  '/whatsapp/templates': typeof DashboardWhatsappTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/about': typeof AboutRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/agents/avatar-manage': typeof DashboardAgentsAvatarManageRoute
  '/_dashboard/agents/avatar-studio': typeof DashboardAgentsAvatarStudioRoute
  '/_dashboard/agents/avatar-sync': typeof DashboardAgentsAvatarSyncRoute
  '/_dashboard/agents/documents': typeof DashboardAgentsDocumentsRoute
  '/_dashboard/agents/hub': typeof DashboardAgentsHubRoute
  '/_dashboard/agents/knowledge': typeof DashboardAgentsKnowledgeRoute
  '/_dashboard/agents/messaging-lab': typeof DashboardAgentsMessagingLabRoute
  '/_dashboard/agents/post-call': typeof DashboardAgentsPostCallRoute
  '/_dashboard/agents/studio': typeof DashboardAgentsStudioRouteWithChildren
  '/_dashboard/agents/voice-health': typeof DashboardAgentsVoiceHealthRoute
  '/_dashboard/agents/voice-lab': typeof DashboardAgentsVoiceLabRoute
  '/_dashboard/agents/workflows': typeof DashboardAgentsWorkflowsRoute
  '/_dashboard/intelligence/autopilot': typeof DashboardIntelligenceAutopilotRoute
  '/_dashboard/intelligence/brain': typeof DashboardIntelligenceBrainRoute
  '/_dashboard/intelligence/conversation': typeof DashboardIntelligenceConversationRoute
  '/_dashboard/intelligence/deal-closer': typeof DashboardIntelligenceDealCloserRoute
  '/_dashboard/intelligence/insights': typeof DashboardIntelligenceInsightsRoute
  '/_dashboard/intelligence/revenue': typeof DashboardIntelligenceRevenueRoute
  '/_dashboard/whatsapp/chatbot': typeof DashboardWhatsappChatbotRoute
  '/_dashboard/whatsapp/contacts': typeof DashboardWhatsappContactsRoute
  '/_dashboard/whatsapp/inbox': typeof DashboardWhatsappInboxRoute
  '/_dashboard/whatsapp/live-agent': typeof DashboardWhatsappLiveAgentRoute
  '/_dashboard/whatsapp/reports': typeof DashboardWhatsappReportsRoute
  '/_dashboard/whatsapp/setup': typeof DashboardWhatsappSetupRoute
  '/_dashboard/whatsapp/tags': typeof DashboardWhatsappTagsRoute
  '/_dashboard/whatsapp/': typeof DashboardWhatsappIndexRoute
  '/_dashboard/agents/studio/$id': typeof DashboardAgentsStudioIdRoute
  '/_dashboard/whatsapp/campaigns/new': typeof DashboardWhatsappCampaignsNewRoute
  '/_dashboard/whatsapp/templates/new': typeof DashboardWhatsappTemplatesNewRoute
  '/_dashboard/whatsapp/campaigns/': typeof DashboardWhatsappCampaignsIndexRoute
  '/_dashboard/whatsapp/templates/': typeof DashboardWhatsappTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/features'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/dashboard'
    | '/agents/avatar-manage'
    | '/agents/avatar-studio'
    | '/agents/avatar-sync'
    | '/agents/documents'
    | '/agents/hub'
    | '/agents/knowledge'
    | '/agents/messaging-lab'
    | '/agents/post-call'
    | '/agents/studio'
    | '/agents/voice-health'
    | '/agents/voice-lab'
    | '/agents/workflows'
    | '/intelligence/autopilot'
    | '/intelligence/brain'
    | '/intelligence/conversation'
    | '/intelligence/deal-closer'
    | '/intelligence/insights'
    | '/intelligence/revenue'
    | '/whatsapp/chatbot'
    | '/whatsapp/contacts'
    | '/whatsapp/inbox'
    | '/whatsapp/live-agent'
    | '/whatsapp/reports'
    | '/whatsapp/setup'
    | '/whatsapp/tags'
    | '/whatsapp/'
    | '/agents/studio/$id'
    | '/whatsapp/campaigns/new'
    | '/whatsapp/templates/new'
    | '/whatsapp/campaigns/'
    | '/whatsapp/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/features'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/dashboard'
    | '/agents/avatar-manage'
    | '/agents/avatar-studio'
    | '/agents/avatar-sync'
    | '/agents/documents'
    | '/agents/hub'
    | '/agents/knowledge'
    | '/agents/messaging-lab'
    | '/agents/post-call'
    | '/agents/studio'
    | '/agents/voice-health'
    | '/agents/voice-lab'
    | '/agents/workflows'
    | '/intelligence/autopilot'
    | '/intelligence/brain'
    | '/intelligence/conversation'
    | '/intelligence/deal-closer'
    | '/intelligence/insights'
    | '/intelligence/revenue'
    | '/whatsapp/chatbot'
    | '/whatsapp/contacts'
    | '/whatsapp/inbox'
    | '/whatsapp/live-agent'
    | '/whatsapp/reports'
    | '/whatsapp/setup'
    | '/whatsapp/tags'
    | '/whatsapp'
    | '/agents/studio/$id'
    | '/whatsapp/campaigns/new'
    | '/whatsapp/templates/new'
    | '/whatsapp/campaigns'
    | '/whatsapp/templates'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/about'
    | '/features'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/_dashboard/dashboard'
    | '/_dashboard/agents/avatar-manage'
    | '/_dashboard/agents/avatar-studio'
    | '/_dashboard/agents/avatar-sync'
    | '/_dashboard/agents/documents'
    | '/_dashboard/agents/hub'
    | '/_dashboard/agents/knowledge'
    | '/_dashboard/agents/messaging-lab'
    | '/_dashboard/agents/post-call'
    | '/_dashboard/agents/studio'
    | '/_dashboard/agents/voice-health'
    | '/_dashboard/agents/voice-lab'
    | '/_dashboard/agents/workflows'
    | '/_dashboard/intelligence/autopilot'
    | '/_dashboard/intelligence/brain'
    | '/_dashboard/intelligence/conversation'
    | '/_dashboard/intelligence/deal-closer'
    | '/_dashboard/intelligence/insights'
    | '/_dashboard/intelligence/revenue'
    | '/_dashboard/whatsapp/chatbot'
    | '/_dashboard/whatsapp/contacts'
    | '/_dashboard/whatsapp/inbox'
    | '/_dashboard/whatsapp/live-agent'
    | '/_dashboard/whatsapp/reports'
    | '/_dashboard/whatsapp/setup'
    | '/_dashboard/whatsapp/tags'
    | '/_dashboard/whatsapp/'
    | '/_dashboard/agents/studio/$id'
    | '/_dashboard/whatsapp/campaigns/new'
    | '/_dashboard/whatsapp/templates/new'
    | '/_dashboard/whatsapp/campaigns/'
    | '/_dashboard/whatsapp/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  AboutRoute: typeof AboutRoute
  FeaturesRoute: typeof FeaturesRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/whatsapp/': {
      id: '/_dashboard/whatsapp/'
      path: '/whatsapp'
      fullPath: '/whatsapp/'
      preLoaderRoute: typeof DashboardWhatsappIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/whatsapp/tags': {
      id: '/_dashboard/whatsapp/tags'
      path: '/whatsapp/tags'
      fullPath: '/whatsapp/tags'
      preLoaderRoute: typeof DashboardWhatsappTagsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/whatsapp/setup': {
      id: '/_dashboard/whatsapp/setup'
      path: '/whatsapp/setup'
      fullPath: '/whatsapp/setup'
      preLoaderRoute: typeof DashboardWhatsappSetupRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/whatsapp/reports': {
      id: '/_dashboard/whatsapp/reports'
      path: '/whatsapp/reports'
      fullPath: '/whatsapp/reports'
      preLoaderRoute: typeof DashboardWhatsappReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/whatsapp/live-agent': {
      id: '/_dashboard/whatsapp/live-agent'
      path: '/whatsapp/live-agent'
      fullPath: '/whatsapp/live-agent'
      preLoaderRoute: typeof DashboardWhatsappLiveAgentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/whatsapp/inbox': {
      id: '/_dashboard/whatsapp/inbox'
      path: '/whatsapp/inbox'
      fullPath: '/whatsapp/inbox'
      preLoaderRoute: typeof DashboardWhatsappInboxRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/whatsapp/contacts': {
      id: '/_dashboard/whatsapp/contacts'
      path: '/whatsapp/contacts'
      fullPath: '/whatsapp/contacts'
      preLoaderRoute: typeof DashboardWhatsappContactsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/whatsapp/chatbot': {
      id: '/_dashboard/whatsapp/chatbot'
      path: '/whatsapp/chatbot'
      fullPath: '/whatsapp/chatbot'
      preLoaderRoute: typeof DashboardWhatsappChatbotRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/intelligence/revenue': {
      id: '/_dashboard/intelligence/revenue'
      path: '/intelligence/revenue'
      fullPath: '/intelligence/revenue'
      preLoaderRoute: typeof DashboardIntelligenceRevenueRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/intelligence/insights': {
      id: '/_dashboard/intelligence/insights'
      path: '/intelligence/insights'
      fullPath: '/intelligence/insights'
      preLoaderRoute: typeof DashboardIntelligenceInsightsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/intelligence/deal-closer': {
      id: '/_dashboard/intelligence/deal-closer'
      path: '/intelligence/deal-closer'
      fullPath: '/intelligence/deal-closer'
      preLoaderRoute: typeof DashboardIntelligenceDealCloserRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/intelligence/conversation': {
      id: '/_dashboard/intelligence/conversation'
      path: '/intelligence/conversation'
      fullPath: '/intelligence/conversation'
      preLoaderRoute: typeof DashboardIntelligenceConversationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/intelligence/brain': {
      id: '/_dashboard/intelligence/brain'
      path: '/intelligence/brain'
      fullPath: '/intelligence/brain'
      preLoaderRoute: typeof DashboardIntelligenceBrainRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/intelligence/autopilot': {
      id: '/_dashboard/intelligence/autopilot'
      path: '/intelligence/autopilot'
      fullPath: '/intelligence/autopilot'
      preLoaderRoute: typeof DashboardIntelligenceAutopilotRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agents/workflows': {
      id: '/_dashboard/agents/workflows'
      path: '/agents/workflows'
      fullPath: '/agents/workflows'
      preLoaderRoute: typeof DashboardAgentsWorkflowsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agents/voice-lab': {
      id: '/_dashboard/agents/voice-lab'
      path: '/agents/voice-lab'
      fullPath: '/agents/voice-lab'
      preLoaderRoute: typeof DashboardAgentsVoiceLabRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agents/voice-health': {
      id: '/_dashboard/agents/voice-health'
      path: '/agents/voice-health'
      fullPath: '/agents/voice-health'
      preLoaderRoute: typeof DashboardAgentsVoiceHealthRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agents/studio': {
      id: '/_dashboard/agents/studio'
      path: '/agents/studio'
      fullPath: '/agents/studio'
      preLoaderRoute: typeof DashboardAgentsStudioRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agents/post-call': {
      id: '/_dashboard/agents/post-call'
      path: '/agents/post-call'
      fullPath: '/agents/post-call'
      preLoaderRoute: typeof DashboardAgentsPostCallRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agents/messaging-lab': {
      id: '/_dashboard/agents/messaging-lab'
      path: '/agents/messaging-lab'
      fullPath: '/agents/messaging-lab'
      preLoaderRoute: typeof DashboardAgentsMessagingLabRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agents/knowledge': {
      id: '/_dashboard/agents/knowledge'
      path: '/agents/knowledge'
      fullPath: '/agents/knowledge'
      preLoaderRoute: typeof DashboardAgentsKnowledgeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agents/hub': {
      id: '/_dashboard/agents/hub'
      path: '/agents/hub'
      fullPath: '/agents/hub'
      preLoaderRoute: typeof DashboardAgentsHubRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agents/documents': {
      id: '/_dashboard/agents/documents'
      path: '/agents/documents'
      fullPath: '/agents/documents'
      preLoaderRoute: typeof DashboardAgentsDocumentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agents/avatar-sync': {
      id: '/_dashboard/agents/avatar-sync'
      path: '/agents/avatar-sync'
      fullPath: '/agents/avatar-sync'
      preLoaderRoute: typeof DashboardAgentsAvatarSyncRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agents/avatar-studio': {
      id: '/_dashboard/agents/avatar-studio'
      path: '/agents/avatar-studio'
      fullPath: '/agents/avatar-studio'
      preLoaderRoute: typeof DashboardAgentsAvatarStudioRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agents/avatar-manage': {
      id: '/_dashboard/agents/avatar-manage'
      path: '/agents/avatar-manage'
      fullPath: '/agents/avatar-manage'
      preLoaderRoute: typeof DashboardAgentsAvatarManageRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/whatsapp/templates/': {
      id: '/_dashboard/whatsapp/templates/'
      path: '/whatsapp/templates'
      fullPath: '/whatsapp/templates/'
      preLoaderRoute: typeof DashboardWhatsappTemplatesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/whatsapp/campaigns/': {
      id: '/_dashboard/whatsapp/campaigns/'
      path: '/whatsapp/campaigns'
      fullPath: '/whatsapp/campaigns/'
      preLoaderRoute: typeof DashboardWhatsappCampaignsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/whatsapp/templates/new': {
      id: '/_dashboard/whatsapp/templates/new'
      path: '/whatsapp/templates/new'
      fullPath: '/whatsapp/templates/new'
      preLoaderRoute: typeof DashboardWhatsappTemplatesNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/whatsapp/campaigns/new': {
      id: '/_dashboard/whatsapp/campaigns/new'
      path: '/whatsapp/campaigns/new'
      fullPath: '/whatsapp/campaigns/new'
      preLoaderRoute: typeof DashboardWhatsappCampaignsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agents/studio/$id': {
      id: '/_dashboard/agents/studio/$id'
      path: '/$id'
      fullPath: '/agents/studio/$id'
      preLoaderRoute: typeof DashboardAgentsStudioIdRouteImport
      parentRoute: typeof DashboardAgentsStudioRoute
    }
  }
}

interface DashboardAgentsStudioRouteChildren {
  DashboardAgentsStudioIdRoute: typeof DashboardAgentsStudioIdRoute
}

const DashboardAgentsStudioRouteChildren: DashboardAgentsStudioRouteChildren = {
  DashboardAgentsStudioIdRoute: DashboardAgentsStudioIdRoute,
}

const DashboardAgentsStudioRouteWithChildren =
  DashboardAgentsStudioRoute._addFileChildren(
    DashboardAgentsStudioRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardAgentsAvatarManageRoute: typeof DashboardAgentsAvatarManageRoute
  DashboardAgentsAvatarStudioRoute: typeof DashboardAgentsAvatarStudioRoute
  DashboardAgentsAvatarSyncRoute: typeof DashboardAgentsAvatarSyncRoute
  DashboardAgentsDocumentsRoute: typeof DashboardAgentsDocumentsRoute
  DashboardAgentsHubRoute: typeof DashboardAgentsHubRoute
  DashboardAgentsKnowledgeRoute: typeof DashboardAgentsKnowledgeRoute
  DashboardAgentsMessagingLabRoute: typeof DashboardAgentsMessagingLabRoute
  DashboardAgentsPostCallRoute: typeof DashboardAgentsPostCallRoute
  DashboardAgentsStudioRoute: typeof DashboardAgentsStudioRouteWithChildren
  DashboardAgentsVoiceHealthRoute: typeof DashboardAgentsVoiceHealthRoute
  DashboardAgentsVoiceLabRoute: typeof DashboardAgentsVoiceLabRoute
  DashboardAgentsWorkflowsRoute: typeof DashboardAgentsWorkflowsRoute
  DashboardIntelligenceAutopilotRoute: typeof DashboardIntelligenceAutopilotRoute
  DashboardIntelligenceBrainRoute: typeof DashboardIntelligenceBrainRoute
  DashboardIntelligenceConversationRoute: typeof DashboardIntelligenceConversationRoute
  DashboardIntelligenceDealCloserRoute: typeof DashboardIntelligenceDealCloserRoute
  DashboardIntelligenceInsightsRoute: typeof DashboardIntelligenceInsightsRoute
  DashboardIntelligenceRevenueRoute: typeof DashboardIntelligenceRevenueRoute
  DashboardWhatsappChatbotRoute: typeof DashboardWhatsappChatbotRoute
  DashboardWhatsappContactsRoute: typeof DashboardWhatsappContactsRoute
  DashboardWhatsappInboxRoute: typeof DashboardWhatsappInboxRoute
  DashboardWhatsappLiveAgentRoute: typeof DashboardWhatsappLiveAgentRoute
  DashboardWhatsappReportsRoute: typeof DashboardWhatsappReportsRoute
  DashboardWhatsappSetupRoute: typeof DashboardWhatsappSetupRoute
  DashboardWhatsappTagsRoute: typeof DashboardWhatsappTagsRoute
  DashboardWhatsappIndexRoute: typeof DashboardWhatsappIndexRoute
  DashboardWhatsappCampaignsNewRoute: typeof DashboardWhatsappCampaignsNewRoute
  DashboardWhatsappTemplatesNewRoute: typeof DashboardWhatsappTemplatesNewRoute
  DashboardWhatsappCampaignsIndexRoute: typeof DashboardWhatsappCampaignsIndexRoute
  DashboardWhatsappTemplatesIndexRoute: typeof DashboardWhatsappTemplatesIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardAgentsAvatarManageRoute: DashboardAgentsAvatarManageRoute,
  DashboardAgentsAvatarStudioRoute: DashboardAgentsAvatarStudioRoute,
  DashboardAgentsAvatarSyncRoute: DashboardAgentsAvatarSyncRoute,
  DashboardAgentsDocumentsRoute: DashboardAgentsDocumentsRoute,
  DashboardAgentsHubRoute: DashboardAgentsHubRoute,
  DashboardAgentsKnowledgeRoute: DashboardAgentsKnowledgeRoute,
  DashboardAgentsMessagingLabRoute: DashboardAgentsMessagingLabRoute,
  DashboardAgentsPostCallRoute: DashboardAgentsPostCallRoute,
  DashboardAgentsStudioRoute: DashboardAgentsStudioRouteWithChildren,
  DashboardAgentsVoiceHealthRoute: DashboardAgentsVoiceHealthRoute,
  DashboardAgentsVoiceLabRoute: DashboardAgentsVoiceLabRoute,
  DashboardAgentsWorkflowsRoute: DashboardAgentsWorkflowsRoute,
  DashboardIntelligenceAutopilotRoute: DashboardIntelligenceAutopilotRoute,
  DashboardIntelligenceBrainRoute: DashboardIntelligenceBrainRoute,
  DashboardIntelligenceConversationRoute:
    DashboardIntelligenceConversationRoute,
  DashboardIntelligenceDealCloserRoute: DashboardIntelligenceDealCloserRoute,
  DashboardIntelligenceInsightsRoute: DashboardIntelligenceInsightsRoute,
  DashboardIntelligenceRevenueRoute: DashboardIntelligenceRevenueRoute,
  DashboardWhatsappChatbotRoute: DashboardWhatsappChatbotRoute,
  DashboardWhatsappContactsRoute: DashboardWhatsappContactsRoute,
  DashboardWhatsappInboxRoute: DashboardWhatsappInboxRoute,
  DashboardWhatsappLiveAgentRoute: DashboardWhatsappLiveAgentRoute,
  DashboardWhatsappReportsRoute: DashboardWhatsappReportsRoute,
  DashboardWhatsappSetupRoute: DashboardWhatsappSetupRoute,
  DashboardWhatsappTagsRoute: DashboardWhatsappTagsRoute,
  DashboardWhatsappIndexRoute: DashboardWhatsappIndexRoute,
  DashboardWhatsappCampaignsNewRoute: DashboardWhatsappCampaignsNewRoute,
  DashboardWhatsappTemplatesNewRoute: DashboardWhatsappTemplatesNewRoute,
  DashboardWhatsappCampaignsIndexRoute: DashboardWhatsappCampaignsIndexRoute,
  DashboardWhatsappTemplatesIndexRoute: DashboardWhatsappTemplatesIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  AboutRoute: AboutRoute,
  FeaturesRoute: FeaturesRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
