/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard.dashboard'
import { Route as DashboardWhatsappIndexRouteImport } from './routes/_dashboard.whatsapp.index'
import { Route as DashboardWebsiteChatIndexRouteImport } from './routes/_dashboard.website-chat.index'
import { Route as DashboardSmsIndexRouteImport } from './routes/_dashboard.sms.index'
import { Route as DashboardEmailIndexRouteImport } from './routes/_dashboard.email.index'
import { Route as DashboardWhatsappTagsRouteImport } from './routes/_dashboard.whatsapp.tags'
import { Route as DashboardWhatsappSetupRouteImport } from './routes/_dashboard.whatsapp.setup'
import { Route as DashboardWhatsappReportsRouteImport } from './routes/_dashboard.whatsapp.reports'
import { Route as DashboardWhatsappLiveAgentRouteImport } from './routes/_dashboard.whatsapp.live-agent'
import { Route as DashboardWhatsappInboxRouteImport } from './routes/_dashboard.whatsapp.inbox'
import { Route as DashboardWhatsappContactsRouteImport } from './routes/_dashboard.whatsapp.contacts'
import { Route as DashboardWhatsappChatbotRouteImport } from './routes/_dashboard.whatsapp.chatbot'
import { Route as DashboardWebsiteChatWidgetsRouteImport } from './routes/_dashboard.website-chat.widgets'
import { Route as DashboardWebsiteChatVisitorsRouteImport } from './routes/_dashboard.website-chat.visitors'
import { Route as DashboardWebsiteChatReportsRouteImport } from './routes/_dashboard.website-chat.reports'
import { Route as DashboardWebsiteChatConversationsRouteImport } from './routes/_dashboard.website-chat.conversations'
import { Route as DashboardSmsTemplatesRouteImport } from './routes/_dashboard.sms.templates'
import { Route as DashboardSmsSetupRouteImport } from './routes/_dashboard.sms.setup'
import { Route as DashboardSmsReportsRouteImport } from './routes/_dashboard.sms.reports'
import { Route as DashboardSmsInboxRouteImport } from './routes/_dashboard.sms.inbox'
import { Route as DashboardSmsContactsRouteImport } from './routes/_dashboard.sms.contacts'
import { Route as DashboardSmsCampaignsRouteImport } from './routes/_dashboard.sms.campaigns'
import { Route as DashboardIntelligenceRevenueRouteImport } from './routes/_dashboard.intelligence.revenue'
import { Route as DashboardIntelligenceInsightsRouteImport } from './routes/_dashboard.intelligence.insights'
import { Route as DashboardIntelligenceDealCloserRouteImport } from './routes/_dashboard.intelligence.deal-closer'
import { Route as DashboardIntelligenceConversationRouteImport } from './routes/_dashboard.intelligence.conversation'
import { Route as DashboardIntelligenceBrainRouteImport } from './routes/_dashboard.intelligence.brain'
import { Route as DashboardIntelligenceAutopilotRouteImport } from './routes/_dashboard.intelligence.autopilot'
import { Route as DashboardInstagramTrendsRouteImport } from './routes/_dashboard.instagram.trends'
import { Route as DashboardInstagramCreateContentRouteImport } from './routes/_dashboard.instagram.create-content'
import { Route as DashboardInstagramContentPlannerRouteImport } from './routes/_dashboard.instagram.content-planner'
import { Route as DashboardEngageUpcomingCallsRouteImport } from './routes/_dashboard.engage.upcoming-calls'
import { Route as DashboardEngageTeamRouteImport } from './routes/_dashboard.engage.team'
import { Route as DashboardEngageRemindersRouteImport } from './routes/_dashboard.engage.reminders'
import { Route as DashboardEngageLiveMonitoringRouteImport } from './routes/_dashboard.engage.live-monitoring'
import { Route as DashboardEngageLeadsRouteImport } from './routes/_dashboard.engage.leads'
import { Route as DashboardEngageCallStatusRouteImport } from './routes/_dashboard.engage.call-status'
import { Route as DashboardEngageCallScriptsRouteImport } from './routes/_dashboard.engage.call-scripts'
import { Route as DashboardEngageCallHistoryRouteImport } from './routes/_dashboard.engage.call-history'
import { Route as DashboardEngageAdvancedAnalyticsRouteImport } from './routes/_dashboard.engage.advanced-analytics'
import { Route as DashboardEmailTestRouteImport } from './routes/_dashboard.email.test'
import { Route as DashboardEmailTemplatesRouteImport } from './routes/_dashboard.email.templates'
import { Route as DashboardEmailSetupRouteImport } from './routes/_dashboard.email.setup'
import { Route as DashboardEmailReportsRouteImport } from './routes/_dashboard.email.reports'
import { Route as DashboardEmailProvidersRouteImport } from './routes/_dashboard.email.providers'
import { Route as DashboardEmailContactsRouteImport } from './routes/_dashboard.email.contacts'
import { Route as DashboardEmailCampaignsRouteImport } from './routes/_dashboard.email.campaigns'
import { Route as DashboardEmailAutomationRouteImport } from './routes/_dashboard.email.automation'
import { Route as DashboardAgentsWorkflowsRouteImport } from './routes/_dashboard.agents.workflows'
import { Route as DashboardAgentsVoiceLabRouteImport } from './routes/_dashboard.agents.voice-lab'
import { Route as DashboardAgentsVoiceHealthRouteImport } from './routes/_dashboard.agents.voice-health'
import { Route as DashboardAgentsStudioRouteImport } from './routes/_dashboard.agents.studio'
import { Route as DashboardAgentsPostCallRouteImport } from './routes/_dashboard.agents.post-call'
import { Route as DashboardAgentsMessagingLabRouteImport } from './routes/_dashboard.agents.messaging-lab'
import { Route as DashboardAgentsKnowledgeRouteImport } from './routes/_dashboard.agents.knowledge'
import { Route as DashboardAgentsHubRouteImport } from './routes/_dashboard.agents.hub'
import { Route as DashboardAgentsDocumentsRouteImport } from './routes/_dashboard.agents.documents'
import { Route as DashboardAgentsAvatarSyncRouteImport } from './routes/_dashboard.agents.avatar-sync'
import { Route as DashboardAgentsAvatarStudioRouteImport } from './routes/_dashboard.agents.avatar-studio'
import { Route as DashboardAgentsAvatarManageRouteImport } from './routes/_dashboard.agents.avatar-manage'
import { Route as DashboardWhatsappTemplatesIndexRouteImport } from './routes/_dashboard.whatsapp.templates.index'
import { Route as DashboardWhatsappCampaignsIndexRouteImport } from './routes/_dashboard.whatsapp.campaigns.index'
import { Route as DashboardWhatsappTemplatesNewRouteImport } from './routes/_dashboard.whatsapp.templates.new'
import { Route as DashboardWhatsappCampaignsNewRouteImport } from './routes/_dashboard.whatsapp.campaigns.new'
import { Route as DashboardAgentsStudioIdRouteImport } from './routes/_dashboard.agents.studio.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWhatsappIndexRoute = DashboardWhatsappIndexRouteImport.update({
  id: '/whatsapp/',
  path: '/whatsapp/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWebsiteChatIndexRoute =
  DashboardWebsiteChatIndexRouteImport.update({
    id: '/website-chat/',
    path: '/website-chat/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSmsIndexRoute = DashboardSmsIndexRouteImport.update({
  id: '/sms/',
  path: '/sms/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEmailIndexRoute = DashboardEmailIndexRouteImport.update({
  id: '/email/',
  path: '/email/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWhatsappTagsRoute = DashboardWhatsappTagsRouteImport.update({
  id: '/whatsapp/tags',
  path: '/whatsapp/tags',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWhatsappSetupRoute = DashboardWhatsappSetupRouteImport.update({
  id: '/whatsapp/setup',
  path: '/whatsapp/setup',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWhatsappReportsRoute =
  DashboardWhatsappReportsRouteImport.update({
    id: '/whatsapp/reports',
    path: '/whatsapp/reports',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardWhatsappLiveAgentRoute =
  DashboardWhatsappLiveAgentRouteImport.update({
    id: '/whatsapp/live-agent',
    path: '/whatsapp/live-agent',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardWhatsappInboxRoute = DashboardWhatsappInboxRouteImport.update({
  id: '/whatsapp/inbox',
  path: '/whatsapp/inbox',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWhatsappContactsRoute =
  DashboardWhatsappContactsRouteImport.update({
    id: '/whatsapp/contacts',
    path: '/whatsapp/contacts',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardWhatsappChatbotRoute =
  DashboardWhatsappChatbotRouteImport.update({
    id: '/whatsapp/chatbot',
    path: '/whatsapp/chatbot',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardWebsiteChatWidgetsRoute =
  DashboardWebsiteChatWidgetsRouteImport.update({
    id: '/website-chat/widgets',
    path: '/website-chat/widgets',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardWebsiteChatVisitorsRoute =
  DashboardWebsiteChatVisitorsRouteImport.update({
    id: '/website-chat/visitors',
    path: '/website-chat/visitors',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardWebsiteChatReportsRoute =
  DashboardWebsiteChatReportsRouteImport.update({
    id: '/website-chat/reports',
    path: '/website-chat/reports',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardWebsiteChatConversationsRoute =
  DashboardWebsiteChatConversationsRouteImport.update({
    id: '/website-chat/conversations',
    path: '/website-chat/conversations',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSmsTemplatesRoute = DashboardSmsTemplatesRouteImport.update({
  id: '/sms/templates',
  path: '/sms/templates',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSmsSetupRoute = DashboardSmsSetupRouteImport.update({
  id: '/sms/setup',
  path: '/sms/setup',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSmsReportsRoute = DashboardSmsReportsRouteImport.update({
  id: '/sms/reports',
  path: '/sms/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSmsInboxRoute = DashboardSmsInboxRouteImport.update({
  id: '/sms/inbox',
  path: '/sms/inbox',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSmsContactsRoute = DashboardSmsContactsRouteImport.update({
  id: '/sms/contacts',
  path: '/sms/contacts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSmsCampaignsRoute = DashboardSmsCampaignsRouteImport.update({
  id: '/sms/campaigns',
  path: '/sms/campaigns',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIntelligenceRevenueRoute =
  DashboardIntelligenceRevenueRouteImport.update({
    id: '/intelligence/revenue',
    path: '/intelligence/revenue',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardIntelligenceInsightsRoute =
  DashboardIntelligenceInsightsRouteImport.update({
    id: '/intelligence/insights',
    path: '/intelligence/insights',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardIntelligenceDealCloserRoute =
  DashboardIntelligenceDealCloserRouteImport.update({
    id: '/intelligence/deal-closer',
    path: '/intelligence/deal-closer',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardIntelligenceConversationRoute =
  DashboardIntelligenceConversationRouteImport.update({
    id: '/intelligence/conversation',
    path: '/intelligence/conversation',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardIntelligenceBrainRoute =
  DashboardIntelligenceBrainRouteImport.update({
    id: '/intelligence/brain',
    path: '/intelligence/brain',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardIntelligenceAutopilotRoute =
  DashboardIntelligenceAutopilotRouteImport.update({
    id: '/intelligence/autopilot',
    path: '/intelligence/autopilot',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardInstagramTrendsRoute =
  DashboardInstagramTrendsRouteImport.update({
    id: '/instagram/trends',
    path: '/instagram/trends',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardInstagramCreateContentRoute =
  DashboardInstagramCreateContentRouteImport.update({
    id: '/instagram/create-content',
    path: '/instagram/create-content',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardInstagramContentPlannerRoute =
  DashboardInstagramContentPlannerRouteImport.update({
    id: '/instagram/content-planner',
    path: '/instagram/content-planner',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardEngageUpcomingCallsRoute =
  DashboardEngageUpcomingCallsRouteImport.update({
    id: '/engage/upcoming-calls',
    path: '/engage/upcoming-calls',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardEngageTeamRoute = DashboardEngageTeamRouteImport.update({
  id: '/engage/team',
  path: '/engage/team',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEngageRemindersRoute =
  DashboardEngageRemindersRouteImport.update({
    id: '/engage/reminders',
    path: '/engage/reminders',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardEngageLiveMonitoringRoute =
  DashboardEngageLiveMonitoringRouteImport.update({
    id: '/engage/live-monitoring',
    path: '/engage/live-monitoring',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardEngageLeadsRoute = DashboardEngageLeadsRouteImport.update({
  id: '/engage/leads',
  path: '/engage/leads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEngageCallStatusRoute =
  DashboardEngageCallStatusRouteImport.update({
    id: '/engage/call-status',
    path: '/engage/call-status',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardEngageCallScriptsRoute =
  DashboardEngageCallScriptsRouteImport.update({
    id: '/engage/call-scripts',
    path: '/engage/call-scripts',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardEngageCallHistoryRoute =
  DashboardEngageCallHistoryRouteImport.update({
    id: '/engage/call-history',
    path: '/engage/call-history',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardEngageAdvancedAnalyticsRoute =
  DashboardEngageAdvancedAnalyticsRouteImport.update({
    id: '/engage/advanced-analytics',
    path: '/engage/advanced-analytics',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardEmailTestRoute = DashboardEmailTestRouteImport.update({
  id: '/email/test',
  path: '/email/test',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEmailTemplatesRoute = DashboardEmailTemplatesRouteImport.update({
  id: '/email/templates',
  path: '/email/templates',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEmailSetupRoute = DashboardEmailSetupRouteImport.update({
  id: '/email/setup',
  path: '/email/setup',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEmailReportsRoute = DashboardEmailReportsRouteImport.update({
  id: '/email/reports',
  path: '/email/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEmailProvidersRoute = DashboardEmailProvidersRouteImport.update({
  id: '/email/providers',
  path: '/email/providers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEmailContactsRoute = DashboardEmailContactsRouteImport.update({
  id: '/email/contacts',
  path: '/email/contacts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEmailCampaignsRoute = DashboardEmailCampaignsRouteImport.update({
  id: '/email/campaigns',
  path: '/email/campaigns',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEmailAutomationRoute =
  DashboardEmailAutomationRouteImport.update({
    id: '/email/automation',
    path: '/email/automation',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAgentsWorkflowsRoute =
  DashboardAgentsWorkflowsRouteImport.update({
    id: '/agents/workflows',
    path: '/agents/workflows',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAgentsVoiceLabRoute = DashboardAgentsVoiceLabRouteImport.update({
  id: '/agents/voice-lab',
  path: '/agents/voice-lab',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgentsVoiceHealthRoute =
  DashboardAgentsVoiceHealthRouteImport.update({
    id: '/agents/voice-health',
    path: '/agents/voice-health',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAgentsStudioRoute = DashboardAgentsStudioRouteImport.update({
  id: '/agents/studio',
  path: '/agents/studio',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgentsPostCallRoute = DashboardAgentsPostCallRouteImport.update({
  id: '/agents/post-call',
  path: '/agents/post-call',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgentsMessagingLabRoute =
  DashboardAgentsMessagingLabRouteImport.update({
    id: '/agents/messaging-lab',
    path: '/agents/messaging-lab',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAgentsKnowledgeRoute =
  DashboardAgentsKnowledgeRouteImport.update({
    id: '/agents/knowledge',
    path: '/agents/knowledge',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAgentsHubRoute = DashboardAgentsHubRouteImport.update({
  id: '/agents/hub',
  path: '/agents/hub',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgentsDocumentsRoute =
  DashboardAgentsDocumentsRouteImport.update({
    id: '/agents/documents',
    path: '/agents/documents',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAgentsAvatarSyncRoute =
  DashboardAgentsAvatarSyncRouteImport.update({
    id: '/agents/avatar-sync',
    path: '/agents/avatar-sync',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAgentsAvatarStudioRoute =
  DashboardAgentsAvatarStudioRouteImport.update({
    id: '/agents/avatar-studio',
    path: '/agents/avatar-studio',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAgentsAvatarManageRoute =
  DashboardAgentsAvatarManageRouteImport.update({
    id: '/agents/avatar-manage',
    path: '/agents/avatar-manage',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardWhatsappTemplatesIndexRoute =
  DashboardWhatsappTemplatesIndexRouteImport.update({
    id: '/whatsapp/templates/',
    path: '/whatsapp/templates/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardWhatsappCampaignsIndexRoute =
  DashboardWhatsappCampaignsIndexRouteImport.update({
    id: '/whatsapp/campaigns/',
    path: '/whatsapp/campaigns/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardWhatsappTemplatesNewRoute =
  DashboardWhatsappTemplatesNewRouteImport.update({
    id: '/whatsapp/templates/new',
    path: '/whatsapp/templates/new',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardWhatsappCampaignsNewRoute =
  DashboardWhatsappCampaignsNewRouteImport.update({
    id: '/whatsapp/campaigns/new',
    path: '/whatsapp/campaigns/new',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAgentsStudioIdRoute = DashboardAgentsStudioIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardAgentsStudioRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/agents/avatar-manage': typeof DashboardAgentsAvatarManageRoute
  '/agents/avatar-studio': typeof DashboardAgentsAvatarStudioRoute
  '/agents/avatar-sync': typeof DashboardAgentsAvatarSyncRoute
  '/agents/documents': typeof DashboardAgentsDocumentsRoute
  '/agents/hub': typeof DashboardAgentsHubRoute
  '/agents/knowledge': typeof DashboardAgentsKnowledgeRoute
  '/agents/messaging-lab': typeof DashboardAgentsMessagingLabRoute
  '/agents/post-call': typeof DashboardAgentsPostCallRoute
  '/agents/studio': typeof DashboardAgentsStudioRouteWithChildren
  '/agents/voice-health': typeof DashboardAgentsVoiceHealthRoute
  '/agents/voice-lab': typeof DashboardAgentsVoiceLabRoute
  '/agents/workflows': typeof DashboardAgentsWorkflowsRoute
  '/email/automation': typeof DashboardEmailAutomationRoute
  '/email/campaigns': typeof DashboardEmailCampaignsRoute
  '/email/contacts': typeof DashboardEmailContactsRoute
  '/email/providers': typeof DashboardEmailProvidersRoute
  '/email/reports': typeof DashboardEmailReportsRoute
  '/email/setup': typeof DashboardEmailSetupRoute
  '/email/templates': typeof DashboardEmailTemplatesRoute
  '/email/test': typeof DashboardEmailTestRoute
  '/engage/advanced-analytics': typeof DashboardEngageAdvancedAnalyticsRoute
  '/engage/call-history': typeof DashboardEngageCallHistoryRoute
  '/engage/call-scripts': typeof DashboardEngageCallScriptsRoute
  '/engage/call-status': typeof DashboardEngageCallStatusRoute
  '/engage/leads': typeof DashboardEngageLeadsRoute
  '/engage/live-monitoring': typeof DashboardEngageLiveMonitoringRoute
  '/engage/reminders': typeof DashboardEngageRemindersRoute
  '/engage/team': typeof DashboardEngageTeamRoute
  '/engage/upcoming-calls': typeof DashboardEngageUpcomingCallsRoute
  '/instagram/content-planner': typeof DashboardInstagramContentPlannerRoute
  '/instagram/create-content': typeof DashboardInstagramCreateContentRoute
  '/instagram/trends': typeof DashboardInstagramTrendsRoute
  '/intelligence/autopilot': typeof DashboardIntelligenceAutopilotRoute
  '/intelligence/brain': typeof DashboardIntelligenceBrainRoute
  '/intelligence/conversation': typeof DashboardIntelligenceConversationRoute
  '/intelligence/deal-closer': typeof DashboardIntelligenceDealCloserRoute
  '/intelligence/insights': typeof DashboardIntelligenceInsightsRoute
  '/intelligence/revenue': typeof DashboardIntelligenceRevenueRoute
  '/sms/campaigns': typeof DashboardSmsCampaignsRoute
  '/sms/contacts': typeof DashboardSmsContactsRoute
  '/sms/inbox': typeof DashboardSmsInboxRoute
  '/sms/reports': typeof DashboardSmsReportsRoute
  '/sms/setup': typeof DashboardSmsSetupRoute
  '/sms/templates': typeof DashboardSmsTemplatesRoute
  '/website-chat/conversations': typeof DashboardWebsiteChatConversationsRoute
  '/website-chat/reports': typeof DashboardWebsiteChatReportsRoute
  '/website-chat/visitors': typeof DashboardWebsiteChatVisitorsRoute
  '/website-chat/widgets': typeof DashboardWebsiteChatWidgetsRoute
  '/whatsapp/chatbot': typeof DashboardWhatsappChatbotRoute
  '/whatsapp/contacts': typeof DashboardWhatsappContactsRoute
  '/whatsapp/inbox': typeof DashboardWhatsappInboxRoute
  '/whatsapp/live-agent': typeof DashboardWhatsappLiveAgentRoute
  '/whatsapp/reports': typeof DashboardWhatsappReportsRoute
  '/whatsapp/setup': typeof DashboardWhatsappSetupRoute
  '/whatsapp/tags': typeof DashboardWhatsappTagsRoute
  '/email/': typeof DashboardEmailIndexRoute
  '/sms/': typeof DashboardSmsIndexRoute
  '/website-chat/': typeof DashboardWebsiteChatIndexRoute
  '/whatsapp/': typeof DashboardWhatsappIndexRoute
  '/agents/studio/$id': typeof DashboardAgentsStudioIdRoute
  '/whatsapp/campaigns/new': typeof DashboardWhatsappCampaignsNewRoute
  '/whatsapp/templates/new': typeof DashboardWhatsappTemplatesNewRoute
  '/whatsapp/campaigns/': typeof DashboardWhatsappCampaignsIndexRoute
  '/whatsapp/templates/': typeof DashboardWhatsappTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/agents/avatar-manage': typeof DashboardAgentsAvatarManageRoute
  '/agents/avatar-studio': typeof DashboardAgentsAvatarStudioRoute
  '/agents/avatar-sync': typeof DashboardAgentsAvatarSyncRoute
  '/agents/documents': typeof DashboardAgentsDocumentsRoute
  '/agents/hub': typeof DashboardAgentsHubRoute
  '/agents/knowledge': typeof DashboardAgentsKnowledgeRoute
  '/agents/messaging-lab': typeof DashboardAgentsMessagingLabRoute
  '/agents/post-call': typeof DashboardAgentsPostCallRoute
  '/agents/studio': typeof DashboardAgentsStudioRouteWithChildren
  '/agents/voice-health': typeof DashboardAgentsVoiceHealthRoute
  '/agents/voice-lab': typeof DashboardAgentsVoiceLabRoute
  '/agents/workflows': typeof DashboardAgentsWorkflowsRoute
  '/email/automation': typeof DashboardEmailAutomationRoute
  '/email/campaigns': typeof DashboardEmailCampaignsRoute
  '/email/contacts': typeof DashboardEmailContactsRoute
  '/email/providers': typeof DashboardEmailProvidersRoute
  '/email/reports': typeof DashboardEmailReportsRoute
  '/email/setup': typeof DashboardEmailSetupRoute
  '/email/templates': typeof DashboardEmailTemplatesRoute
  '/email/test': typeof DashboardEmailTestRoute
  '/engage/advanced-analytics': typeof DashboardEngageAdvancedAnalyticsRoute
  '/engage/call-history': typeof DashboardEngageCallHistoryRoute
  '/engage/call-scripts': typeof DashboardEngageCallScriptsRoute
  '/engage/call-status': typeof DashboardEngageCallStatusRoute
  '/engage/leads': typeof DashboardEngageLeadsRoute
  '/engage/live-monitoring': typeof DashboardEngageLiveMonitoringRoute
  '/engage/reminders': typeof DashboardEngageRemindersRoute
  '/engage/team': typeof DashboardEngageTeamRoute
  '/engage/upcoming-calls': typeof DashboardEngageUpcomingCallsRoute
  '/instagram/content-planner': typeof DashboardInstagramContentPlannerRoute
  '/instagram/create-content': typeof DashboardInstagramCreateContentRoute
  '/instagram/trends': typeof DashboardInstagramTrendsRoute
  '/intelligence/autopilot': typeof DashboardIntelligenceAutopilotRoute
  '/intelligence/brain': typeof DashboardIntelligenceBrainRoute
  '/intelligence/conversation': typeof DashboardIntelligenceConversationRoute
  '/intelligence/deal-closer': typeof DashboardIntelligenceDealCloserRoute
  '/intelligence/insights': typeof DashboardIntelligenceInsightsRoute
  '/intelligence/revenue': typeof DashboardIntelligenceRevenueRoute
  '/sms/campaigns': typeof DashboardSmsCampaignsRoute
  '/sms/contacts': typeof DashboardSmsContactsRoute
  '/sms/inbox': typeof DashboardSmsInboxRoute
  '/sms/reports': typeof DashboardSmsReportsRoute
  '/sms/setup': typeof DashboardSmsSetupRoute
  '/sms/templates': typeof DashboardSmsTemplatesRoute
  '/website-chat/conversations': typeof DashboardWebsiteChatConversationsRoute
  '/website-chat/reports': typeof DashboardWebsiteChatReportsRoute
  '/website-chat/visitors': typeof DashboardWebsiteChatVisitorsRoute
  '/website-chat/widgets': typeof DashboardWebsiteChatWidgetsRoute
  '/whatsapp/chatbot': typeof DashboardWhatsappChatbotRoute
  '/whatsapp/contacts': typeof DashboardWhatsappContactsRoute
  '/whatsapp/inbox': typeof DashboardWhatsappInboxRoute
  '/whatsapp/live-agent': typeof DashboardWhatsappLiveAgentRoute
  '/whatsapp/reports': typeof DashboardWhatsappReportsRoute
  '/whatsapp/setup': typeof DashboardWhatsappSetupRoute
  '/whatsapp/tags': typeof DashboardWhatsappTagsRoute
  '/email': typeof DashboardEmailIndexRoute
  '/sms': typeof DashboardSmsIndexRoute
  '/website-chat': typeof DashboardWebsiteChatIndexRoute
  '/whatsapp': typeof DashboardWhatsappIndexRoute
  '/agents/studio/$id': typeof DashboardAgentsStudioIdRoute
  '/whatsapp/campaigns/new': typeof DashboardWhatsappCampaignsNewRoute
  '/whatsapp/templates/new': typeof DashboardWhatsappTemplatesNewRoute
  '/whatsapp/campaigns': typeof DashboardWhatsappCampaignsIndexRoute
  '/whatsapp/templates': typeof DashboardWhatsappTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/about': typeof AboutRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/agents/avatar-manage': typeof DashboardAgentsAvatarManageRoute
  '/_dashboard/agents/avatar-studio': typeof DashboardAgentsAvatarStudioRoute
  '/_dashboard/agents/avatar-sync': typeof DashboardAgentsAvatarSyncRoute
  '/_dashboard/agents/documents': typeof DashboardAgentsDocumentsRoute
  '/_dashboard/agents/hub': typeof DashboardAgentsHubRoute
  '/_dashboard/agents/knowledge': typeof DashboardAgentsKnowledgeRoute
  '/_dashboard/agents/messaging-lab': typeof DashboardAgentsMessagingLabRoute
  '/_dashboard/agents/post-call': typeof DashboardAgentsPostCallRoute
  '/_dashboard/agents/studio': typeof DashboardAgentsStudioRouteWithChildren
  '/_dashboard/agents/voice-health': typeof DashboardAgentsVoiceHealthRoute
  '/_dashboard/agents/voice-lab': typeof DashboardAgentsVoiceLabRoute
  '/_dashboard/agents/workflows': typeof DashboardAgentsWorkflowsRoute
  '/_dashboard/email/automation': typeof DashboardEmailAutomationRoute
  '/_dashboard/email/campaigns': typeof DashboardEmailCampaignsRoute
  '/_dashboard/email/contacts': typeof DashboardEmailContactsRoute
  '/_dashboard/email/providers': typeof DashboardEmailProvidersRoute
  '/_dashboard/email/reports': typeof DashboardEmailReportsRoute
  '/_dashboard/email/setup': typeof DashboardEmailSetupRoute
  '/_dashboard/email/templates': typeof DashboardEmailTemplatesRoute
  '/_dashboard/email/test': typeof DashboardEmailTestRoute
  '/_dashboard/engage/advanced-analytics': typeof DashboardEngageAdvancedAnalyticsRoute
  '/_dashboard/engage/call-history': typeof DashboardEngageCallHistoryRoute
  '/_dashboard/engage/call-scripts': typeof DashboardEngageCallScriptsRoute
  '/_dashboard/engage/call-status': typeof DashboardEngageCallStatusRoute
  '/_dashboard/engage/leads': typeof DashboardEngageLeadsRoute
  '/_dashboard/engage/live-monitoring': typeof DashboardEngageLiveMonitoringRoute
  '/_dashboard/engage/reminders': typeof DashboardEngageRemindersRoute
  '/_dashboard/engage/team': typeof DashboardEngageTeamRoute
  '/_dashboard/engage/upcoming-calls': typeof DashboardEngageUpcomingCallsRoute
  '/_dashboard/instagram/content-planner': typeof DashboardInstagramContentPlannerRoute
  '/_dashboard/instagram/create-content': typeof DashboardInstagramCreateContentRoute
  '/_dashboard/instagram/trends': typeof DashboardInstagramTrendsRoute
  '/_dashboard/intelligence/autopilot': typeof DashboardIntelligenceAutopilotRoute
  '/_dashboard/intelligence/brain': typeof DashboardIntelligenceBrainRoute
  '/_dashboard/intelligence/conversation': typeof DashboardIntelligenceConversationRoute
  '/_dashboard/intelligence/deal-closer': typeof DashboardIntelligenceDealCloserRoute
  '/_dashboard/intelligence/insights': typeof DashboardIntelligenceInsightsRoute
  '/_dashboard/intelligence/revenue': typeof DashboardIntelligenceRevenueRoute
  '/_dashboard/sms/campaigns': typeof DashboardSmsCampaignsRoute
  '/_dashboard/sms/contacts': typeof DashboardSmsContactsRoute
  '/_dashboard/sms/inbox': typeof DashboardSmsInboxRoute
  '/_dashboard/sms/reports': typeof DashboardSmsReportsRoute
  '/_dashboard/sms/setup': typeof DashboardSmsSetupRoute
  '/_dashboard/sms/templates': typeof DashboardSmsTemplatesRoute
  '/_dashboard/website-chat/conversations': typeof DashboardWebsiteChatConversationsRoute
  '/_dashboard/website-chat/reports': typeof DashboardWebsiteChatReportsRoute
  '/_dashboard/website-chat/visitors': typeof DashboardWebsiteChatVisitorsRoute
  '/_dashboard/website-chat/widgets': typeof DashboardWebsiteChatWidgetsRoute
  '/_dashboard/whatsapp/chatbot': typeof DashboardWhatsappChatbotRoute
  '/_dashboard/whatsapp/contacts': typeof DashboardWhatsappContactsRoute
  '/_dashboard/whatsapp/inbox': typeof DashboardWhatsappInboxRoute
  '/_dashboard/whatsapp/live-agent': typeof DashboardWhatsappLiveAgentRoute
  '/_dashboard/whatsapp/reports': typeof DashboardWhatsappReportsRoute
  '/_dashboard/whatsapp/setup': typeof DashboardWhatsappSetupRoute
  '/_dashboard/whatsapp/tags': typeof DashboardWhatsappTagsRoute
  '/_dashboard/email/': typeof DashboardEmailIndexRoute
  '/_dashboard/sms/': typeof DashboardSmsIndexRoute
  '/_dashboard/website-chat/': typeof DashboardWebsiteChatIndexRoute
  '/_dashboard/whatsapp/': typeof DashboardWhatsappIndexRoute
  '/_dashboard/agents/studio/$id': typeof DashboardAgentsStudioIdRoute
  '/_dashboard/whatsapp/campaigns/new': typeof DashboardWhatsappCampaignsNewRoute
  '/_dashboard/whatsapp/templates/new': typeof DashboardWhatsappTemplatesNewRoute
  '/_dashboard/whatsapp/campaigns/': typeof DashboardWhatsappCampaignsIndexRoute
  '/_dashboard/whatsapp/templates/': typeof DashboardWhatsappTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/features'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/dashboard'
    | '/agents/avatar-manage'
    | '/agents/avatar-studio'
    | '/agents/avatar-sync'
    | '/agents/documents'
    | '/agents/hub'
    | '/agents/knowledge'
    | '/agents/messaging-lab'
    | '/agents/post-call'
    | '/agents/studio'
    | '/agents/voice-health'
    | '/agents/voice-lab'
    | '/agents/workflows'
    | '/email/automation'
    | '/email/campaigns'
    | '/email/contacts'
    | '/email/providers'
    | '/email/reports'
    | '/email/setup'
    | '/email/templates'
    | '/email/test'
    | '/engage/advanced-analytics'
    | '/engage/call-history'
    | '/engage/call-scripts'
    | '/engage/call-status'
    | '/engage/leads'
    | '/engage/live-monitoring'
    | '/engage/reminders'
    | '/engage/team'
    | '/engage/upcoming-calls'
    | '/instagram/content-planner'
    | '/instagram/create-content'
    | '/instagram/trends'
    | '/intelligence/autopilot'
    | '/intelligence/brain'
    | '/intelligence/conversation'
    | '/intelligence/deal-closer'
    | '/intelligence/insights'
    | '/intelligence/revenue'
    | '/sms/campaigns'
    | '/sms/contacts'
    | '/sms/inbox'
    | '/sms/reports'
    | '/sms/setup'
    | '/sms/templates'
    | '/website-chat/conversations'
    | '/website-chat/reports'
    | '/website-chat/visitors'
    | '/website-chat/widgets'
    | '/whatsapp/chatbot'
    | '/whatsapp/contacts'
    | '/whatsapp/inbox'
    | '/whatsapp/live-agent'
    | '/whatsapp/reports'
    | '/whatsapp/setup'
    | '/whatsapp/tags'
    | '/email/'
    | '/sms/'
    | '/website-chat/'
    | '/whatsapp/'
    | '/agents/studio/$id'
    | '/whatsapp/campaigns/new'
    | '/whatsapp/templates/new'
    | '/whatsapp/campaigns/'
    | '/whatsapp/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/features'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/dashboard'
    | '/agents/avatar-manage'
    | '/agents/avatar-studio'
    | '/agents/avatar-sync'
    | '/agents/documents'
    | '/agents/hub'
    | '/agents/knowledge'
    | '/agents/messaging-lab'
    | '/agents/post-call'
    | '/agents/studio'
    | '/agents/voice-health'
    | '/agents/voice-lab'
    | '/agents/workflows'
    | '/email/automation'
    | '/email/campaigns'
    | '/email/contacts'
    | '/email/providers'
    | '/email/reports'
    | '/email/setup'
    | '/email/templates'
    | '/email/test'
    | '/engage/advanced-analytics'
    | '/engage/call-history'
    | '/engage/call-scripts'
    | '/engage/call-status'
    | '/engage/leads'
    | '/engage/live-monitoring'
    | '/engage/reminders'
    | '/engage/team'
    | '/engage/upcoming-calls'
    | '/instagram/content-planner'
    | '/instagram/create-content'
    | '/instagram/trends'
    | '/intelligence/autopilot'
    | '/intelligence/brain'
    | '/intelligence/conversation'
    | '/intelligence/deal-closer'
    | '/intelligence/insights'
    | '/intelligence/revenue'
    | '/sms/campaigns'
    | '/sms/contacts'
    | '/sms/inbox'
    | '/sms/reports'
    | '/sms/setup'
    | '/sms/templates'
    | '/website-chat/conversations'
    | '/website-chat/reports'
    | '/website-chat/visitors'
    | '/website-chat/widgets'
    | '/whatsapp/chatbot'
    | '/whatsapp/contacts'
    | '/whatsapp/inbox'
    | '/whatsapp/live-agent'
    | '/whatsapp/reports'
    | '/whatsapp/setup'
    | '/whatsapp/tags'
    | '/email'
    | '/sms'
    | '/website-chat'
    | '/whatsapp'
    | '/agents/studio/$id'
    | '/whatsapp/campaigns/new'
    | '/whatsapp/templates/new'
    | '/whatsapp/campaigns'
    | '/whatsapp/templates'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/about'
    | '/features'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/_dashboard/dashboard'
    | '/_dashboard/agents/avatar-manage'
    | '/_dashboard/agents/avatar-studio'
    | '/_dashboard/agents/avatar-sync'
    | '/_dashboard/agents/documents'
    | '/_dashboard/agents/hub'
    | '/_dashboard/agents/knowledge'
    | '/_dashboard/agents/messaging-lab'
    | '/_dashboard/agents/post-call'
    | '/_dashboard/agents/studio'
    | '/_dashboard/agents/voice-health'
    | '/_dashboard/agents/voice-lab'
    | '/_dashboard/agents/workflows'
    | '/_dashboard/email/automation'
    | '/_dashboard/email/campaigns'
    | '/_dashboard/email/contacts'
    | '/_dashboard/email/providers'
    | '/_dashboard/email/reports'
    | '/_dashboard/email/setup'
    | '/_dashboard/email/templates'
    | '/_dashboard/email/test'
    | '/_dashboard/engage/advanced-analytics'
    | '/_dashboard/engage/call-history'
    | '/_dashboard/engage/call-scripts'
    | '/_dashboard/engage/call-status'
    | '/_dashboard/engage/leads'
    | '/_dashboard/engage/live-monitoring'
    | '/_dashboard/engage/reminders'
    | '/_dashboard/engage/team'
    | '/_dashboard/engage/upcoming-calls'
    | '/_dashboard/instagram/content-planner'
    | '/_dashboard/instagram/create-content'
    | '/_dashboard/instagram/trends'
    | '/_dashboard/intelligence/autopilot'
    | '/_dashboard/intelligence/brain'
    | '/_dashboard/intelligence/conversation'
    | '/_dashboard/intelligence/deal-closer'
    | '/_dashboard/intelligence/insights'
    | '/_dashboard/intelligence/revenue'
    | '/_dashboard/sms/campaigns'
    | '/_dashboard/sms/contacts'
    | '/_dashboard/sms/inbox'
    | '/_dashboard/sms/reports'
    | '/_dashboard/sms/setup'
    | '/_dashboard/sms/templates'
    | '/_dashboard/website-chat/conversations'
    | '/_dashboard/website-chat/reports'
    | '/_dashboard/website-chat/visitors'
    | '/_dashboard/website-chat/widgets'
    | '/_dashboard/whatsapp/chatbot'
    | '/_dashboard/whatsapp/contacts'
    | '/_dashboard/whatsapp/inbox'
    | '/_dashboard/whatsapp/live-agent'
    | '/_dashboard/whatsapp/reports'
    | '/_dashboard/whatsapp/setup'
    | '/_dashboard/whatsapp/tags'
    | '/_dashboard/email/'
    | '/_dashboard/sms/'
    | '/_dashboard/website-chat/'
    | '/_dashboard/whatsapp/'
    | '/_dashboard/agents/studio/$id'
    | '/_dashboard/whatsapp/campaigns/new'
    | '/_dashboard/whatsapp/templates/new'
    | '/_dashboard/whatsapp/campaigns/'
    | '/_dashboard/whatsapp/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  AboutRoute: typeof AboutRoute
  FeaturesRoute: typeof FeaturesRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/whatsapp/': {
      id: '/_dashboard/whatsapp/'
      path: '/whatsapp'
      fullPath: '/whatsapp/'
      preLoaderRoute: typeof DashboardWhatsappIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/website-chat/': {
      id: '/_dashboard/website-chat/'
      path: '/website-chat'
      fullPath: '/website-chat/'
      preLoaderRoute: typeof DashboardWebsiteChatIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/sms/': {
      id: '/_dashboard/sms/'
      path: '/sms'
      fullPath: '/sms/'
      preLoaderRoute: typeof DashboardSmsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/email/': {
      id: '/_dashboard/email/'
      path: '/email'
      fullPath: '/email/'
      preLoaderRoute: typeof DashboardEmailIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/whatsapp/tags': {
      id: '/_dashboard/whatsapp/tags'
      path: '/whatsapp/tags'
      fullPath: '/whatsapp/tags'
      preLoaderRoute: typeof DashboardWhatsappTagsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/whatsapp/setup': {
      id: '/_dashboard/whatsapp/setup'
      path: '/whatsapp/setup'
      fullPath: '/whatsapp/setup'
      preLoaderRoute: typeof DashboardWhatsappSetupRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/whatsapp/reports': {
      id: '/_dashboard/whatsapp/reports'
      path: '/whatsapp/reports'
      fullPath: '/whatsapp/reports'
      preLoaderRoute: typeof DashboardWhatsappReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/whatsapp/live-agent': {
      id: '/_dashboard/whatsapp/live-agent'
      path: '/whatsapp/live-agent'
      fullPath: '/whatsapp/live-agent'
      preLoaderRoute: typeof DashboardWhatsappLiveAgentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/whatsapp/inbox': {
      id: '/_dashboard/whatsapp/inbox'
      path: '/whatsapp/inbox'
      fullPath: '/whatsapp/inbox'
      preLoaderRoute: typeof DashboardWhatsappInboxRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/whatsapp/contacts': {
      id: '/_dashboard/whatsapp/contacts'
      path: '/whatsapp/contacts'
      fullPath: '/whatsapp/contacts'
      preLoaderRoute: typeof DashboardWhatsappContactsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/whatsapp/chatbot': {
      id: '/_dashboard/whatsapp/chatbot'
      path: '/whatsapp/chatbot'
      fullPath: '/whatsapp/chatbot'
      preLoaderRoute: typeof DashboardWhatsappChatbotRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/website-chat/widgets': {
      id: '/_dashboard/website-chat/widgets'
      path: '/website-chat/widgets'
      fullPath: '/website-chat/widgets'
      preLoaderRoute: typeof DashboardWebsiteChatWidgetsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/website-chat/visitors': {
      id: '/_dashboard/website-chat/visitors'
      path: '/website-chat/visitors'
      fullPath: '/website-chat/visitors'
      preLoaderRoute: typeof DashboardWebsiteChatVisitorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/website-chat/reports': {
      id: '/_dashboard/website-chat/reports'
      path: '/website-chat/reports'
      fullPath: '/website-chat/reports'
      preLoaderRoute: typeof DashboardWebsiteChatReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/website-chat/conversations': {
      id: '/_dashboard/website-chat/conversations'
      path: '/website-chat/conversations'
      fullPath: '/website-chat/conversations'
      preLoaderRoute: typeof DashboardWebsiteChatConversationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/sms/templates': {
      id: '/_dashboard/sms/templates'
      path: '/sms/templates'
      fullPath: '/sms/templates'
      preLoaderRoute: typeof DashboardSmsTemplatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/sms/setup': {
      id: '/_dashboard/sms/setup'
      path: '/sms/setup'
      fullPath: '/sms/setup'
      preLoaderRoute: typeof DashboardSmsSetupRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/sms/reports': {
      id: '/_dashboard/sms/reports'
      path: '/sms/reports'
      fullPath: '/sms/reports'
      preLoaderRoute: typeof DashboardSmsReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/sms/inbox': {
      id: '/_dashboard/sms/inbox'
      path: '/sms/inbox'
      fullPath: '/sms/inbox'
      preLoaderRoute: typeof DashboardSmsInboxRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/sms/contacts': {
      id: '/_dashboard/sms/contacts'
      path: '/sms/contacts'
      fullPath: '/sms/contacts'
      preLoaderRoute: typeof DashboardSmsContactsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/sms/campaigns': {
      id: '/_dashboard/sms/campaigns'
      path: '/sms/campaigns'
      fullPath: '/sms/campaigns'
      preLoaderRoute: typeof DashboardSmsCampaignsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/intelligence/revenue': {
      id: '/_dashboard/intelligence/revenue'
      path: '/intelligence/revenue'
      fullPath: '/intelligence/revenue'
      preLoaderRoute: typeof DashboardIntelligenceRevenueRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/intelligence/insights': {
      id: '/_dashboard/intelligence/insights'
      path: '/intelligence/insights'
      fullPath: '/intelligence/insights'
      preLoaderRoute: typeof DashboardIntelligenceInsightsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/intelligence/deal-closer': {
      id: '/_dashboard/intelligence/deal-closer'
      path: '/intelligence/deal-closer'
      fullPath: '/intelligence/deal-closer'
      preLoaderRoute: typeof DashboardIntelligenceDealCloserRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/intelligence/conversation': {
      id: '/_dashboard/intelligence/conversation'
      path: '/intelligence/conversation'
      fullPath: '/intelligence/conversation'
      preLoaderRoute: typeof DashboardIntelligenceConversationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/intelligence/brain': {
      id: '/_dashboard/intelligence/brain'
      path: '/intelligence/brain'
      fullPath: '/intelligence/brain'
      preLoaderRoute: typeof DashboardIntelligenceBrainRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/intelligence/autopilot': {
      id: '/_dashboard/intelligence/autopilot'
      path: '/intelligence/autopilot'
      fullPath: '/intelligence/autopilot'
      preLoaderRoute: typeof DashboardIntelligenceAutopilotRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/instagram/trends': {
      id: '/_dashboard/instagram/trends'
      path: '/instagram/trends'
      fullPath: '/instagram/trends'
      preLoaderRoute: typeof DashboardInstagramTrendsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/instagram/create-content': {
      id: '/_dashboard/instagram/create-content'
      path: '/instagram/create-content'
      fullPath: '/instagram/create-content'
      preLoaderRoute: typeof DashboardInstagramCreateContentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/instagram/content-planner': {
      id: '/_dashboard/instagram/content-planner'
      path: '/instagram/content-planner'
      fullPath: '/instagram/content-planner'
      preLoaderRoute: typeof DashboardInstagramContentPlannerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/engage/upcoming-calls': {
      id: '/_dashboard/engage/upcoming-calls'
      path: '/engage/upcoming-calls'
      fullPath: '/engage/upcoming-calls'
      preLoaderRoute: typeof DashboardEngageUpcomingCallsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/engage/team': {
      id: '/_dashboard/engage/team'
      path: '/engage/team'
      fullPath: '/engage/team'
      preLoaderRoute: typeof DashboardEngageTeamRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/engage/reminders': {
      id: '/_dashboard/engage/reminders'
      path: '/engage/reminders'
      fullPath: '/engage/reminders'
      preLoaderRoute: typeof DashboardEngageRemindersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/engage/live-monitoring': {
      id: '/_dashboard/engage/live-monitoring'
      path: '/engage/live-monitoring'
      fullPath: '/engage/live-monitoring'
      preLoaderRoute: typeof DashboardEngageLiveMonitoringRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/engage/leads': {
      id: '/_dashboard/engage/leads'
      path: '/engage/leads'
      fullPath: '/engage/leads'
      preLoaderRoute: typeof DashboardEngageLeadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/engage/call-status': {
      id: '/_dashboard/engage/call-status'
      path: '/engage/call-status'
      fullPath: '/engage/call-status'
      preLoaderRoute: typeof DashboardEngageCallStatusRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/engage/call-scripts': {
      id: '/_dashboard/engage/call-scripts'
      path: '/engage/call-scripts'
      fullPath: '/engage/call-scripts'
      preLoaderRoute: typeof DashboardEngageCallScriptsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/engage/call-history': {
      id: '/_dashboard/engage/call-history'
      path: '/engage/call-history'
      fullPath: '/engage/call-history'
      preLoaderRoute: typeof DashboardEngageCallHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/engage/advanced-analytics': {
      id: '/_dashboard/engage/advanced-analytics'
      path: '/engage/advanced-analytics'
      fullPath: '/engage/advanced-analytics'
      preLoaderRoute: typeof DashboardEngageAdvancedAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/email/test': {
      id: '/_dashboard/email/test'
      path: '/email/test'
      fullPath: '/email/test'
      preLoaderRoute: typeof DashboardEmailTestRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/email/templates': {
      id: '/_dashboard/email/templates'
      path: '/email/templates'
      fullPath: '/email/templates'
      preLoaderRoute: typeof DashboardEmailTemplatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/email/setup': {
      id: '/_dashboard/email/setup'
      path: '/email/setup'
      fullPath: '/email/setup'
      preLoaderRoute: typeof DashboardEmailSetupRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/email/reports': {
      id: '/_dashboard/email/reports'
      path: '/email/reports'
      fullPath: '/email/reports'
      preLoaderRoute: typeof DashboardEmailReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/email/providers': {
      id: '/_dashboard/email/providers'
      path: '/email/providers'
      fullPath: '/email/providers'
      preLoaderRoute: typeof DashboardEmailProvidersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/email/contacts': {
      id: '/_dashboard/email/contacts'
      path: '/email/contacts'
      fullPath: '/email/contacts'
      preLoaderRoute: typeof DashboardEmailContactsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/email/campaigns': {
      id: '/_dashboard/email/campaigns'
      path: '/email/campaigns'
      fullPath: '/email/campaigns'
      preLoaderRoute: typeof DashboardEmailCampaignsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/email/automation': {
      id: '/_dashboard/email/automation'
      path: '/email/automation'
      fullPath: '/email/automation'
      preLoaderRoute: typeof DashboardEmailAutomationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agents/workflows': {
      id: '/_dashboard/agents/workflows'
      path: '/agents/workflows'
      fullPath: '/agents/workflows'
      preLoaderRoute: typeof DashboardAgentsWorkflowsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agents/voice-lab': {
      id: '/_dashboard/agents/voice-lab'
      path: '/agents/voice-lab'
      fullPath: '/agents/voice-lab'
      preLoaderRoute: typeof DashboardAgentsVoiceLabRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agents/voice-health': {
      id: '/_dashboard/agents/voice-health'
      path: '/agents/voice-health'
      fullPath: '/agents/voice-health'
      preLoaderRoute: typeof DashboardAgentsVoiceHealthRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agents/studio': {
      id: '/_dashboard/agents/studio'
      path: '/agents/studio'
      fullPath: '/agents/studio'
      preLoaderRoute: typeof DashboardAgentsStudioRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agents/post-call': {
      id: '/_dashboard/agents/post-call'
      path: '/agents/post-call'
      fullPath: '/agents/post-call'
      preLoaderRoute: typeof DashboardAgentsPostCallRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agents/messaging-lab': {
      id: '/_dashboard/agents/messaging-lab'
      path: '/agents/messaging-lab'
      fullPath: '/agents/messaging-lab'
      preLoaderRoute: typeof DashboardAgentsMessagingLabRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agents/knowledge': {
      id: '/_dashboard/agents/knowledge'
      path: '/agents/knowledge'
      fullPath: '/agents/knowledge'
      preLoaderRoute: typeof DashboardAgentsKnowledgeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agents/hub': {
      id: '/_dashboard/agents/hub'
      path: '/agents/hub'
      fullPath: '/agents/hub'
      preLoaderRoute: typeof DashboardAgentsHubRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agents/documents': {
      id: '/_dashboard/agents/documents'
      path: '/agents/documents'
      fullPath: '/agents/documents'
      preLoaderRoute: typeof DashboardAgentsDocumentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agents/avatar-sync': {
      id: '/_dashboard/agents/avatar-sync'
      path: '/agents/avatar-sync'
      fullPath: '/agents/avatar-sync'
      preLoaderRoute: typeof DashboardAgentsAvatarSyncRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agents/avatar-studio': {
      id: '/_dashboard/agents/avatar-studio'
      path: '/agents/avatar-studio'
      fullPath: '/agents/avatar-studio'
      preLoaderRoute: typeof DashboardAgentsAvatarStudioRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agents/avatar-manage': {
      id: '/_dashboard/agents/avatar-manage'
      path: '/agents/avatar-manage'
      fullPath: '/agents/avatar-manage'
      preLoaderRoute: typeof DashboardAgentsAvatarManageRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/whatsapp/templates/': {
      id: '/_dashboard/whatsapp/templates/'
      path: '/whatsapp/templates'
      fullPath: '/whatsapp/templates/'
      preLoaderRoute: typeof DashboardWhatsappTemplatesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/whatsapp/campaigns/': {
      id: '/_dashboard/whatsapp/campaigns/'
      path: '/whatsapp/campaigns'
      fullPath: '/whatsapp/campaigns/'
      preLoaderRoute: typeof DashboardWhatsappCampaignsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/whatsapp/templates/new': {
      id: '/_dashboard/whatsapp/templates/new'
      path: '/whatsapp/templates/new'
      fullPath: '/whatsapp/templates/new'
      preLoaderRoute: typeof DashboardWhatsappTemplatesNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/whatsapp/campaigns/new': {
      id: '/_dashboard/whatsapp/campaigns/new'
      path: '/whatsapp/campaigns/new'
      fullPath: '/whatsapp/campaigns/new'
      preLoaderRoute: typeof DashboardWhatsappCampaignsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agents/studio/$id': {
      id: '/_dashboard/agents/studio/$id'
      path: '/$id'
      fullPath: '/agents/studio/$id'
      preLoaderRoute: typeof DashboardAgentsStudioIdRouteImport
      parentRoute: typeof DashboardAgentsStudioRoute
    }
  }
}

interface DashboardAgentsStudioRouteChildren {
  DashboardAgentsStudioIdRoute: typeof DashboardAgentsStudioIdRoute
}

const DashboardAgentsStudioRouteChildren: DashboardAgentsStudioRouteChildren = {
  DashboardAgentsStudioIdRoute: DashboardAgentsStudioIdRoute,
}

const DashboardAgentsStudioRouteWithChildren =
  DashboardAgentsStudioRoute._addFileChildren(
    DashboardAgentsStudioRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardAgentsAvatarManageRoute: typeof DashboardAgentsAvatarManageRoute
  DashboardAgentsAvatarStudioRoute: typeof DashboardAgentsAvatarStudioRoute
  DashboardAgentsAvatarSyncRoute: typeof DashboardAgentsAvatarSyncRoute
  DashboardAgentsDocumentsRoute: typeof DashboardAgentsDocumentsRoute
  DashboardAgentsHubRoute: typeof DashboardAgentsHubRoute
  DashboardAgentsKnowledgeRoute: typeof DashboardAgentsKnowledgeRoute
  DashboardAgentsMessagingLabRoute: typeof DashboardAgentsMessagingLabRoute
  DashboardAgentsPostCallRoute: typeof DashboardAgentsPostCallRoute
  DashboardAgentsStudioRoute: typeof DashboardAgentsStudioRouteWithChildren
  DashboardAgentsVoiceHealthRoute: typeof DashboardAgentsVoiceHealthRoute
  DashboardAgentsVoiceLabRoute: typeof DashboardAgentsVoiceLabRoute
  DashboardAgentsWorkflowsRoute: typeof DashboardAgentsWorkflowsRoute
  DashboardEmailAutomationRoute: typeof DashboardEmailAutomationRoute
  DashboardEmailCampaignsRoute: typeof DashboardEmailCampaignsRoute
  DashboardEmailContactsRoute: typeof DashboardEmailContactsRoute
  DashboardEmailProvidersRoute: typeof DashboardEmailProvidersRoute
  DashboardEmailReportsRoute: typeof DashboardEmailReportsRoute
  DashboardEmailSetupRoute: typeof DashboardEmailSetupRoute
  DashboardEmailTemplatesRoute: typeof DashboardEmailTemplatesRoute
  DashboardEmailTestRoute: typeof DashboardEmailTestRoute
  DashboardEngageAdvancedAnalyticsRoute: typeof DashboardEngageAdvancedAnalyticsRoute
  DashboardEngageCallHistoryRoute: typeof DashboardEngageCallHistoryRoute
  DashboardEngageCallScriptsRoute: typeof DashboardEngageCallScriptsRoute
  DashboardEngageCallStatusRoute: typeof DashboardEngageCallStatusRoute
  DashboardEngageLeadsRoute: typeof DashboardEngageLeadsRoute
  DashboardEngageLiveMonitoringRoute: typeof DashboardEngageLiveMonitoringRoute
  DashboardEngageRemindersRoute: typeof DashboardEngageRemindersRoute
  DashboardEngageTeamRoute: typeof DashboardEngageTeamRoute
  DashboardEngageUpcomingCallsRoute: typeof DashboardEngageUpcomingCallsRoute
  DashboardInstagramContentPlannerRoute: typeof DashboardInstagramContentPlannerRoute
  DashboardInstagramCreateContentRoute: typeof DashboardInstagramCreateContentRoute
  DashboardInstagramTrendsRoute: typeof DashboardInstagramTrendsRoute
  DashboardIntelligenceAutopilotRoute: typeof DashboardIntelligenceAutopilotRoute
  DashboardIntelligenceBrainRoute: typeof DashboardIntelligenceBrainRoute
  DashboardIntelligenceConversationRoute: typeof DashboardIntelligenceConversationRoute
  DashboardIntelligenceDealCloserRoute: typeof DashboardIntelligenceDealCloserRoute
  DashboardIntelligenceInsightsRoute: typeof DashboardIntelligenceInsightsRoute
  DashboardIntelligenceRevenueRoute: typeof DashboardIntelligenceRevenueRoute
  DashboardSmsCampaignsRoute: typeof DashboardSmsCampaignsRoute
  DashboardSmsContactsRoute: typeof DashboardSmsContactsRoute
  DashboardSmsInboxRoute: typeof DashboardSmsInboxRoute
  DashboardSmsReportsRoute: typeof DashboardSmsReportsRoute
  DashboardSmsSetupRoute: typeof DashboardSmsSetupRoute
  DashboardSmsTemplatesRoute: typeof DashboardSmsTemplatesRoute
  DashboardWebsiteChatConversationsRoute: typeof DashboardWebsiteChatConversationsRoute
  DashboardWebsiteChatReportsRoute: typeof DashboardWebsiteChatReportsRoute
  DashboardWebsiteChatVisitorsRoute: typeof DashboardWebsiteChatVisitorsRoute
  DashboardWebsiteChatWidgetsRoute: typeof DashboardWebsiteChatWidgetsRoute
  DashboardWhatsappChatbotRoute: typeof DashboardWhatsappChatbotRoute
  DashboardWhatsappContactsRoute: typeof DashboardWhatsappContactsRoute
  DashboardWhatsappInboxRoute: typeof DashboardWhatsappInboxRoute
  DashboardWhatsappLiveAgentRoute: typeof DashboardWhatsappLiveAgentRoute
  DashboardWhatsappReportsRoute: typeof DashboardWhatsappReportsRoute
  DashboardWhatsappSetupRoute: typeof DashboardWhatsappSetupRoute
  DashboardWhatsappTagsRoute: typeof DashboardWhatsappTagsRoute
  DashboardEmailIndexRoute: typeof DashboardEmailIndexRoute
  DashboardSmsIndexRoute: typeof DashboardSmsIndexRoute
  DashboardWebsiteChatIndexRoute: typeof DashboardWebsiteChatIndexRoute
  DashboardWhatsappIndexRoute: typeof DashboardWhatsappIndexRoute
  DashboardWhatsappCampaignsNewRoute: typeof DashboardWhatsappCampaignsNewRoute
  DashboardWhatsappTemplatesNewRoute: typeof DashboardWhatsappTemplatesNewRoute
  DashboardWhatsappCampaignsIndexRoute: typeof DashboardWhatsappCampaignsIndexRoute
  DashboardWhatsappTemplatesIndexRoute: typeof DashboardWhatsappTemplatesIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardAgentsAvatarManageRoute: DashboardAgentsAvatarManageRoute,
  DashboardAgentsAvatarStudioRoute: DashboardAgentsAvatarStudioRoute,
  DashboardAgentsAvatarSyncRoute: DashboardAgentsAvatarSyncRoute,
  DashboardAgentsDocumentsRoute: DashboardAgentsDocumentsRoute,
  DashboardAgentsHubRoute: DashboardAgentsHubRoute,
  DashboardAgentsKnowledgeRoute: DashboardAgentsKnowledgeRoute,
  DashboardAgentsMessagingLabRoute: DashboardAgentsMessagingLabRoute,
  DashboardAgentsPostCallRoute: DashboardAgentsPostCallRoute,
  DashboardAgentsStudioRoute: DashboardAgentsStudioRouteWithChildren,
  DashboardAgentsVoiceHealthRoute: DashboardAgentsVoiceHealthRoute,
  DashboardAgentsVoiceLabRoute: DashboardAgentsVoiceLabRoute,
  DashboardAgentsWorkflowsRoute: DashboardAgentsWorkflowsRoute,
  DashboardEmailAutomationRoute: DashboardEmailAutomationRoute,
  DashboardEmailCampaignsRoute: DashboardEmailCampaignsRoute,
  DashboardEmailContactsRoute: DashboardEmailContactsRoute,
  DashboardEmailProvidersRoute: DashboardEmailProvidersRoute,
  DashboardEmailReportsRoute: DashboardEmailReportsRoute,
  DashboardEmailSetupRoute: DashboardEmailSetupRoute,
  DashboardEmailTemplatesRoute: DashboardEmailTemplatesRoute,
  DashboardEmailTestRoute: DashboardEmailTestRoute,
  DashboardEngageAdvancedAnalyticsRoute: DashboardEngageAdvancedAnalyticsRoute,
  DashboardEngageCallHistoryRoute: DashboardEngageCallHistoryRoute,
  DashboardEngageCallScriptsRoute: DashboardEngageCallScriptsRoute,
  DashboardEngageCallStatusRoute: DashboardEngageCallStatusRoute,
  DashboardEngageLeadsRoute: DashboardEngageLeadsRoute,
  DashboardEngageLiveMonitoringRoute: DashboardEngageLiveMonitoringRoute,
  DashboardEngageRemindersRoute: DashboardEngageRemindersRoute,
  DashboardEngageTeamRoute: DashboardEngageTeamRoute,
  DashboardEngageUpcomingCallsRoute: DashboardEngageUpcomingCallsRoute,
  DashboardInstagramContentPlannerRoute: DashboardInstagramContentPlannerRoute,
  DashboardInstagramCreateContentRoute: DashboardInstagramCreateContentRoute,
  DashboardInstagramTrendsRoute: DashboardInstagramTrendsRoute,
  DashboardIntelligenceAutopilotRoute: DashboardIntelligenceAutopilotRoute,
  DashboardIntelligenceBrainRoute: DashboardIntelligenceBrainRoute,
  DashboardIntelligenceConversationRoute:
    DashboardIntelligenceConversationRoute,
  DashboardIntelligenceDealCloserRoute: DashboardIntelligenceDealCloserRoute,
  DashboardIntelligenceInsightsRoute: DashboardIntelligenceInsightsRoute,
  DashboardIntelligenceRevenueRoute: DashboardIntelligenceRevenueRoute,
  DashboardSmsCampaignsRoute: DashboardSmsCampaignsRoute,
  DashboardSmsContactsRoute: DashboardSmsContactsRoute,
  DashboardSmsInboxRoute: DashboardSmsInboxRoute,
  DashboardSmsReportsRoute: DashboardSmsReportsRoute,
  DashboardSmsSetupRoute: DashboardSmsSetupRoute,
  DashboardSmsTemplatesRoute: DashboardSmsTemplatesRoute,
  DashboardWebsiteChatConversationsRoute:
    DashboardWebsiteChatConversationsRoute,
  DashboardWebsiteChatReportsRoute: DashboardWebsiteChatReportsRoute,
  DashboardWebsiteChatVisitorsRoute: DashboardWebsiteChatVisitorsRoute,
  DashboardWebsiteChatWidgetsRoute: DashboardWebsiteChatWidgetsRoute,
  DashboardWhatsappChatbotRoute: DashboardWhatsappChatbotRoute,
  DashboardWhatsappContactsRoute: DashboardWhatsappContactsRoute,
  DashboardWhatsappInboxRoute: DashboardWhatsappInboxRoute,
  DashboardWhatsappLiveAgentRoute: DashboardWhatsappLiveAgentRoute,
  DashboardWhatsappReportsRoute: DashboardWhatsappReportsRoute,
  DashboardWhatsappSetupRoute: DashboardWhatsappSetupRoute,
  DashboardWhatsappTagsRoute: DashboardWhatsappTagsRoute,
  DashboardEmailIndexRoute: DashboardEmailIndexRoute,
  DashboardSmsIndexRoute: DashboardSmsIndexRoute,
  DashboardWebsiteChatIndexRoute: DashboardWebsiteChatIndexRoute,
  DashboardWhatsappIndexRoute: DashboardWhatsappIndexRoute,
  DashboardWhatsappCampaignsNewRoute: DashboardWhatsappCampaignsNewRoute,
  DashboardWhatsappTemplatesNewRoute: DashboardWhatsappTemplatesNewRoute,
  DashboardWhatsappCampaignsIndexRoute: DashboardWhatsappCampaignsIndexRoute,
  DashboardWhatsappTemplatesIndexRoute: DashboardWhatsappTemplatesIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  AboutRoute: AboutRoute,
  FeaturesRoute: FeaturesRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
